[package]
name = "groestl-aesni"
version = "0.3.1"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
description = "Hardware-accelerated Groestl hash for x86-64 systems with AES extensions"
documentation = "https://docs.rs/groestl-aesni"
keywords = ["crypto", "groestl", "hash", "digest"]
categories = ["cryptography", "no-std"]
repository = "https://github.com/cryptocorrosion/hashes"
edition = "2021"
rust-version = "1.61"

[dependencies]
block-buffer = "0.9"
digest = "0.9"
lazy_static = { version = "1.2", optional = true }
zerocopy = { version = "0.7", features = ["simd", "derive"] }

[dev-dependencies]
digest = { version = "0.9", features = ["dev"] }

[features]
std = ["lazy_static"]
default = ["std"]

[badges]
travis-ci = { repository = "cryptocorrosion/cryptocorrosion" }
